# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

services:
    #nginx:
        #image: nginx:latest
        #ports:
            #- 8080:80
        #volumes:
            #- ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        #volumes_from:
            #- php
    php:
        build: .
        ports:
            - 8080:8080
        volumes:
            - .:/var/www/html
    mysql:
        image: mysql:latest
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project
